import { grpc } from '@improbable-eng/grpc-web'
import './globals.css'
import { NodeHttpTransport } from '@improbable-eng/grpc-web-node-http-transport'
import { PlayerProvider } from '~/lib/contexts/player-context'


export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

grpc.setDefaultTransport(NodeHttpTransport())

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <head>
                <style>
                    @import url('https://fonts.googleapis.com/css2?family=Darker+Grotesque:wght@300;400;500;700;800;900&display=swap');
                </style>
            </head>
            <body>
                <PlayerProvider>
                    {children}
                </PlayerProvider>
            </body>
        </html>
    )
}
